version: 1.0.{build}
image: Ubuntu1804
services:
- docker
build_script:
- sh: >-
    ls -al var/run/

    sudo docker run --rm -v "${APPVEYOR_BUILD_FOLDER}/:/repo-dir/contents/:ro" -v "/output/:/repo-dir/BuildTarget/:rw" microsoft/dotnet:2.1-sdk-alpine build /repo-dir/contents/Source/UtilPack.Logging