version: 1.0.{build}
image: Ubuntu1804
services:
  - docker
cache:
#  - '/nuget_package_dir'
#  - '/var/lib/docker/image'
environment:
  CS_OUTPUT: '/output/'
init:
  - sh: git config --global core.autocrlf false
build_script:
  - sh: '${APPVEYOR_BUILD_FOLDER}/CI/build.sh'

test_script:
  - sh: '${APPVEYOR_BUILD_FOLDER}/CI/test.sh'
  
deploy_script:
  - sh: '${APPVEYOR_BUILD_FOLDER}/CI/test.sh'