version: '1.0.{build}-{branch}'
image: Ubuntu1804
services:
  - docker
cache:
#  - '/nuget_package_dir'
#  - '/var/lib/docker/image'
environment:
  CS_OUTPUT: '/output/'
  CI_FOLDER: 'CI'
  
artifacts:
  - path: 'bin/*/Release/*.nupkg'
init:
  - sh: git config --global core.autocrlf false
  - sh: appveyor UpdateBuild -Version "1.0.${APPVEYOR_BUILD_NUMBER}-${APPVEYOR_REPO_COMMIT0:8}"
# install:
#   - sh: git submodule update --init --recursive
build_script:
  - sh: '"${APPVEYOR_BUILD_FOLDER}/${CI_FOLDER}/build.sh"'
  - sh: 'sudo chown -R `id -u` "${CS_OUTPUT}"'
  - sh: 'mv "${CS_OUTPUT}/bin" "${APPVEYOR_BUILD_FOLDER}"'
  - sh: 'sudo ls -al "${APPVEYOR_BUILD_FOLDER}"'

test_script:
  - sh: '${APPVEYOR_BUILD_FOLDER}/${CI_FOLDER}/test.sh'
  
deploy_script:
  - sh: '${APPVEYOR_BUILD_FOLDER}/${CI_FOLDER}/deploy.sh'