version: 1.0.{build}
image: Ubuntu1804
services:
  - docker
cache:
  - '/nuget_package_dir'
build_script:
  - sh: >-
      sudo ls -al /var/lib/docker
    
      ${APPVEYOR_BUILD_FOLDER}/CI/build.sh

test_script:
  - sh: '${APPVEYOR_BUILD_FOLDER}/CI/test.sh'
  
deploy_script:
  - sh: '${APPVEYOR_BUILD_FOLDER}/CI/test.sh'